<?php 
// AS CONFIGURAÇÕES SETADAS AQUI, APENAS FAZEM MOSTRA CORES DE EMAIL, MOBILE THEMA, CALCULO DE FRETE COMPRA DIRETA NA LOJA
return array (
  'frete_prod' => '0',
  'config' => 
  array (
    'cart' => 
    array (
      'frete' => '0',
      'direct' => '1',
    ),
    'cupom' => '1',
    'product' => 
    array (
      'buy' => '1',
    ),
    'pedido' => 
    array (
      'obs' => 
      array (
        0 => '0',
        'text' => '',
      ),
      'date' => 
      array (
        'text' => '',
      ),
    ),
    'btn-compra' => 
    array (
      0 => '0',
      'text' => 'ORÇAMENTO',
      'class' => 'btn btn-compra btn-compra-rapida btn-block',
      'class-icon' => 'fa-shopping-cart',
    ),
    'btn-espiar' => 
    array (
      0 => '1',
      'text' => 'ORÇAMENTO',
      'class' => 'btn btn-compra btn-compra-rapida btn-block',
      'class-icon' => 'fa-shopping-cart',
    ),
  ),
  'color001' => '#ffffff',
  'color002' => '#999999',
  'background001' => '#dedede',
  'background002' => '#f3f3f3',
  'theme-color' => '#dedede',
);