on:
  push:
    branches:
      - deploy

name: Deploy CI/CD Distribuidora MSA
jobs:
  job1:
    name: Sync files FTP
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 172.106.0.125
        username: q0qq8b0u
        password: ix6v4Mu09R
        server-dir: public_html/test/
        local-dir: assets/distribuidoramsa/imgs/logo.png

  # job2:
  #   name: Command Remote SSH
  #   runs-on: ubuntu-latest
  #   needs: job1

  #   steps:
  #   - name: Executing remote SSH commands
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: 172.106.0.125
  #       username: q0qq8b0u
  #       password: ix6v4Mu09R
  #       port: 22022
  #       script: |
  #         cd /home/mrmarley/public_html/
  #         composer update -o
  #         chown -R mrmarley:mrmarley /home/mrmarley/public_html

  # job3:
  #   name: GruntJs compress images
  #   runs-on: ubuntu-latest
  #   needs: job2

  #   steps:
  #   - name: Use Node.js 16.x and Clone repository
  #     uses: actions/setup-node@v2

  #     with:
  #       node-version: '16'

  #   - name: Get latest code
  #     uses: actions/checkout@v2

  #   - name: Ajusts directory and Install GruntJs
  #     run: |
  #       cp -r assets/mrmarley/imgs assets/mrmarley/imgs_old
  #       ls -la assets/mrmarley/imgs_old
  #       npm install grunt grunt-contrib-imagemin --save-dev
  #       grunt imagemin:png
  #       grunt imagemin:jpg
  #       rm -rf assets/mrmarley/imgs_old
  #       ls -la assets/mrmarley/imgs

  #   - name: Sync files to images
  #     uses: SamKirkland/FTP-Deploy-Action@4.3.0
  #     with:
  #       server: 162.241.41.45
  #       username: mrmarley
  #       password: mR@4258y867#
  #       local-dir: assets/mrmarley/imgs/
  #       server-dir: public_html/assets/mrmarley/imgs/
