on:
  push:
    branches:
      - deploy

name: Deploy CI/CD Distribuidora MSA
jobs:
  job1:
    name: Sync files FTP
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        #local-dir: assets/distribuidoramsa/imgs/

  job2:
    name: Command Remote SSH
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          cd /home/q0qq8b0u/public_html/app/
          composer update

