on:
  push:
    branches:
      - deploy

name: Deploy CI/CD Distribuidora MSA
jobs:
  job1:
    name: Sync files FTP
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/

  job2:
    name: Command Remote SSH
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 22
        script: |
          cd /home/${{ secrets.ftp_username }}/public_html/app/
          composer update
